[dependencies]

[package]
  cjc-version = "0.60.5"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "thunderlang"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  [package.package-configuration]
