[dependencies]
  iota4cj = { git="https://github.com/gtn1024/iota4cj.git", tag="1.0.0" }

[package]
  cjc-version = "0.60.5"
  compile-option = "--debug-macro"
  description = "nothing here"
  link-option = ""
  name = "thunderlang"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  [package.package-configuration]
